### ISSUE TITLE
how to enable max power?

### ISSUE THREAD

**Issue by appletechgeek** [juvgrfunex/cryo-cooler-controller#3]
heya good day! great job on getting a application going to interface with the cooler.\

 but how can i get it to run at max power without humidity regulation and such? i want to test this on some external hardware and just run some tests in general.

also i thought these TEC's ran at about15 volts for max power and kinda assumed the pcb stepped that up to 15v. 

i have a coolermaster ml360 here that i got torn down to parts.

**Comment by juvgrfunex** [comment]
Hey, thanks for the kind words :)

> but how can i get it to run at max power without humidity regulation and such? 

As far as i know there is no true full power mode supported by these coolers. You can get it to run at 100% in pretty much any realistic use case by setting the target offset to -30.

> also i thought these TEC's ran at about15 volts for max power and kinda assumed the pcb stepped that up to 15v.

The TEC is powered by the 0-12V from the 6pin connector. The controller PCB can only down step the voltage, not increase it. In theory it might be possible to input 15V at the 6pin to get it to run the TEC at up to 15V, but i have not tested that and have no idea if it would work or damage something.
